name: build
on: workflow_dispatch
jobs:
  focal-20_04:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ruby_major_minor: '2.6'
            ruby_version: '2.6.10'
            ruby_sha256: 0dc609f263d49c4176d5725deefc337273676395985b5e017789373e8cadf16e
          - ruby_major_minor: '2.7'
            ruby_version: '2.7.6'
            ruby_sha256: e7203b0cc09442ed2c08936d483f8ac140ec1c72e37bb5c401646b7866cb5d10
          - ruby_major_minor: '3.0'
            ruby_version: '3.0.4'
            ruby_sha256: 70b47c207af04bce9acea262308fb42893d3e244f39a4abc586920a1c723722b
          - ruby_major_minor: '3.1'
            ruby_version: '3.1.2'
            ruby_sha256: 61843112389f02b735428b53bb64cf988ad9fb81858b8248e22e57336f24a83e
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up label values
        id: label-values
        run: |
          echo "created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: '20.04'
          platforms: linux/amd64,linux/arm64
          build-args: |
            RUBY_VERSION=${{ matrix.ruby_version }}
            RUBY_SHA256=${{ matrix.ruby_sha256 }}
          push: true
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ steps.label-values.outputs.created }}
            org.opencontainers.image.description=Ruby ${{ matrix.ruby_version  }} package for ubuntu 20.04 containers
          tags: |
            ghcr.io/${{ github.repository }}:20.04-${{ matrix.ruby_major_minor }}
            ghcr.io/${{ github.repository }}:20.04-${{ matrix.ruby_version }}
